---
id: sprk2012
base_name: how-to-make-clear-code
tags:
- rabbit
- sprk2012
- clear code
presentation_date: 2012/09/16
version: 2012.09.16.5
licenses:
- CC BY 3.0
slideshare_id: how-to-make-clear-code-14288919
speaker_deck_id: how-to-make-clear-code
ustream_id: 25451894
author:
  markup_language: rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
